console: true
org: pauloricardoma
app: hello-sls-framwork
service: hello-sls-framwork
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  hello2:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello2
          method: get
  hello3:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello3
          method: get
